name: Deploy Praxiio
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Run Tests
        run: npm test
        
      - name: Build
        run: npm run build
        
      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          ENVIRONMENT: production
          TIMESTAMP: "2025-08-27 13:06:11"
          DEPLOYER: "prxiio"
        run: |
          echo "Deploying version ${{ github.sha }}"
          echo "Deployed by $DEPLOYER at $TIMESTAMP"
          ./scripts/deploy.sh